# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Logistics"
  url = "#logistics"
  weight = 10
[[main]]
  name = "People"
  url = "#people"
  weight = 20

[[main]]
  name = "Schedule"
  url = "#schedule"
  weight = 30

[[main]]
  name = "Class"
  url="#Class"
  weight = 50
  
[[main]]
  name = "Project"
  url="#Project"
  weight = 60
  
 [[main]]
  name = "Resources"
  url="#Resources"
  weight = 70
  
 [[main]]
  name = "Syllabus"
  url="#Syllabus"
  weight = 80

  
  
# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
